### ISSUE TITLE
bash is not recognized

### ISSUE THREAD

**Issue by GenericGoose** [redthing1/dray#2]
I ran dub init from win10 cmd, added this as dependency, ran dub, get 'bash it not recognized'. there's nothing about this in the instructions

**Comment by EricPoggel** [comment]
I got the same issue.

**Comment by redthing1** [comment]
> I ran dub init from win10 cmd, added this as dependency, ran dub, get 'bash it not recognized'. there's nothing about this in the instructions

This bindings auto build script is designed for Unix, on windows you should build the raylib from linked sources and place the .lib file you get as output (do a static build) in the root of your dray folder within your dub cavhe
